" Jem Bijoux's VIMRC
" Basic VIM Configuration
" WIP (probably forever) 
" 
" This file is divided into the following sections:

" Base {{{

set nocompatible 

" Enable filetype plugins
filetype plugin on
filetype indent on " load filetype-specific indent files 

set encoding=utf8 " Set utf8 encoding/en_US

" Set our backup / swap / undofile locations
set backupdir=~/.vim/tmp/backup//
set directory=~/.vim/tmp/swap//
set undodir=~/.vim/tmp/undo//

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif



" }}}
" Plugins / Pathogen {{{

" Pathogen :: Load up theme vim plugins in the bundle dir
execute pathogen#infect()

" Airline - Status Bar
let g:airline#extensions#tabline#enabled = 1 "Display all buffers when only 1

set laststatus=2 " Always show status line

set modelines=1   " Set file modeline.
let g:airline_powerline_fonts = 1 " Make sure alternate font symbols display



" }}}
" Syntastic Config {{{

" Syntax checking / highlighting

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

" let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Command-T:
" Map the escape key for terminal
" https://github.com/wincent/command-t/blob/master/doc/command-t.txt#L1141

if &term =~ "xterm" || &term =~ "screen"
  let g:CommandTCancelMap = ['<ESC>', '<C-c>']
endif


" }}}
" Theme / Visual Settings {{{
 
syntax on 		" Syntax Highlighting
colorscheme onedark
let g:airline_theme='onedark'



" }}}
" Tab Stop Settings {{{

set expandtab       " tabs are spaces
set tabstop=2       " number of visual spaces per TAB
set softtabstop=2   " number of spaces in tab when editing
set shiftwidth=2    " number of spaces for auto autoindent (>>)



" }}}
" UI Config {{{ 

set relativenumber      " show line numbers
set showcmd             " show command in bottom bar
set cursorline          " highlight current line
set showmatch           " highlight matching [{()}

let &colorcolumn="80,".join(range(120,999),",") " Highlight 80 / Past 120



" }}}
" Searching {{{

set incsearch           " search as characters are entered
set hlsearch            " highlight matches



" }}}
" Folding {{{

set foldenable          " enable folding
set foldlevelstart=10   " open most folds by default
set foldnestmax=10      " 10 nested fold max

set foldmethod=indent   " fold based on indent level 



" }}}
" DiffOrig Command {{{
" 
" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
		  \ | wincmd p | diffthis
endif



" }}}
" Custom Key Mappings {{{

" Open VIMRC for configuration
nnoremap <leader>, :e $MYVIMRC<cr>        " Open vimrc (change settings)
nnoremap <leader>. :source $MYVIMRC<cr>   " Apply vimrc settings changes.

nnoremap <leader>b :NERDTreeToggle<cr>    " Toggle NerdTree
nnoremap <leader><space> :nohlsearch<CR>  " turn off search highlight
nnoremap <leader>s :write<CR>             " Save current file

" Moving Lines Up or Down
" http://vim.wikia.com/wiki/Moving_lines_up_or_down
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
inoremap <A-j> <Esc>:m .+1<CR>==gi
inoremap <A-k> <Esc>:m .-2<CR>==gi
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv

" }}}
" 
" vim:foldmethod=marker:foldlevel=0
