" Jem Bijoux's VIMRC
" Basic VIM Configuration
" WIP (probably forever) 
" 
" This file is divided into the following sections:

" Base {{{

" Disable Vi compatability, not _completely_ pointless...
" http://stackoverflow.com/questions/5845557/in-a-vimrc-is-set-nocompatible-completely-useless
set nocompatible 
set encoding=utf8 " Set utf8 encoding/en_US

" Enable filetype plugins, indenting, syntax
syntax on
filetype on
filetype plugin on
filetype indent on " load filetype-specific indent files 


" Set our backup / swap / undofile locations
set backupdir=~/.vim/tmp/backup//
set directory=~/.vim/tmp/swap//
set undodir=~/.vim/tmp/undo//

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif

set vb       " Use Visual Bell (if available). Make no noise!
set autoread " Reload files changed outside of vim
set wildmenu " :command tab-completion shows additional options
set wildmode=list:longest " command completion acts more like shell
set history=1000 " Keep a longer history
set hidden  " Allow modified buffers to sit in the background:u

runtime macros/matchit.vim  " % key also matches if/else/end/xml tags


" }}}
" Plugins {{{

runtime ./extensions.vim " Source the plugins from an external file

" Status Bar
set laststatus=2 " Always show status line
set modelines=1   " Set file modeline.
" (we also have airline configured in extensions.vim)


" }}}
" Theme / Visual Settings {{{
 
syntax on 		" Syntax Highlighting
colorscheme onedark

" Make mustache/handlebars the default filetype for html
au BufRead,BufNewFile *.html set filetype=mustache



" }}}
" Tab Stop Settings {{{

set expandtab       " tabs are spaces
set tabstop=2       " number of visual spaces per TAB
set softtabstop=2   " number of spaces in tab when editing
set shiftwidth=2    " number of spaces for auto autoindent (>>)



" }}}
" UI Config {{{ 

set relativenumber      " show line numbers
set showcmd             " show command in bottom bar
set cursorline          " highlight current line
set showmatch           " highlight matching [{()}
set listchars=tab:>-,trail:·,eol:¶ " Trailing characters to display

let &colorcolumn="80,".join(range(120,999),",") " Highlight 80 / Past 120



" }}}
" Searching {{{

set hlsearch            " Highlight search terms...
set incsearch           " ...dynamically as they are typed.
set ignorecase          " Ignore case for searching
set smartcase           " Unless you include a capital in the search



" }}}
" Folding {{{

set foldenable          " enable folding
set foldlevelstart=10   " open most folds by default
set foldnestmax=10      " 10 nested fold max

set foldmethod=indent   " fold based on indent level 



" }}}
" DiffOrig Command {{{
" 
" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
		  \ | wincmd p | diffthis
endif



" }}}
" Custom Key Mappings {{{

" Open VIMRC for configuration
nnoremap <leader>, :e $MYVIMRC<cr>        " Open vimrc (change settings)
nnoremap <leader>. :source $MYVIMRC<cr>   " Apply vimrc settings changes.

nnoremap <leader>b :NERDTreeToggle<cr>    " Toggle NerdTree
nnoremap <leader><space> :nohlsearch<CR>  " turn off search highlight
nnoremap <leader>s :write<CR>             " Save current file
nnoremap <silent> <leader>l :set nolist!<CR>  " Toggle invisible characters


" Make scrolling just a little faster.
nnoremap <C-y> 3<C-y>
nnoremap <C-e> 3<C-e>

" Moving Lines Up or Down
" http://vim.wikia.com/wiki/Moving_lines_up_or_down
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
inoremap <A-j> <Esc>:m .+1<CR>==gi
inoremap <A-k> <Esc>:m .-2<CR>==gi
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv
" MacVim Variation (for mac alt-keys that map to specific chars)
nnoremap ∆ :m .+1<CR>==
nnoremap ˚ :m .-2<CR>==
inoremap ∆ <Esc>:m .+1<CR>==gi
inoremap ˚ <Esc>:m .-2<CR>==gi
vnoremap ∆ :m '>+1<CR>gv=gv
vnoremap ˚ :m '<-2<CR>gv=gv
 

" }}}
" 
" vim:foldmethod=marker:foldlevel=0
